/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewDesktop;

import Model.Livro;
import facade.ControleFacadeDesktop;

/**
 *
 * @author alunos
 */
public class Tela_Livro extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Livro
     */
    public Tela_Livro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labeltitulo = new javax.swing.JLabel();
        labelautor = new javax.swing.JLabel();
        labelgenero = new javax.swing.JLabel();
        labeleditora = new javax.swing.JLabel();
        txttitulo = new javax.swing.JTextField();
        txtautor = new javax.swing.JTextField();
        txtgenero = new javax.swing.JTextField();
        txteditora = new javax.swing.JTextField();
        btncadastrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblmensagem = new javax.swing.JLabel();
        txtpreco = new javax.swing.JTextField();
        labelpreco = new javax.swing.JLabel();
        txtidioma = new javax.swing.JTextField();
        labelidioma = new javax.swing.JLabel();
        txtclassificacaoindicativa = new javax.swing.JTextField();
        labelclassificacao = new javax.swing.JLabel();
        labelpublicação = new javax.swing.JLabel();
        txtanopublicacao = new javax.swing.JTextField();
        labelnumero = new javax.swing.JLabel();
        txtnumeropagina = new javax.swing.JTextField();
        btnatualizar = new javax.swing.JButton();
        btndeletar = new javax.swing.JButton();
        labelid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btnconsultarId = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Cadastro Livro");

        labeltitulo.setText("Titulo:");

        labelautor.setText("Autor:");

        labelgenero.setText("Genero:");

        labeleditora.setText("Editora:");

        btncadastrar.setText("CADASTRAR");
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });

        jLabel6.setText("Mensagem:");

        labelpreco.setText("Preço:");

        labelidioma.setText("Idioma:");

        labelclassificacao.setText("Classificação Indicativa:");

        labelpublicação.setText("Ano Publicação:");

        txtanopublicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanopublicacaoActionPerformed(evt);
            }
        });

        labelnumero.setText("Número de Paginas:");

        btnatualizar.setText("ATUALIZAR");
        btnatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizarActionPerformed(evt);
            }
        });

        btndeletar.setText("DELETAR");
        btndeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletarActionPerformed(evt);
            }
        });

        labelid.setText("ID:");

        btnconsultarId.setText("CONSULTAR ID");
        btnconsultarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblmensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btncadastrar)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelpreco)
                                                .addComponent(labelidioma)))
                                        .addComponent(labelclassificacao)
                                        .addComponent(labelnumero)
                                        .addComponent(labelpublicação)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnatualizar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btndeletar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnconsultarId))
                                    .addComponent(txtclassificacaoindicativa, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtidioma, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelid)
                                .addGap(127, 127, 127)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnumeropagina, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtanopublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtautor, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txteditora, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 195, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelgenero)
                        .addComponent(labeleditora)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labeltitulo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                            .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(labelautor))
                    .addGap(213, 213, 213)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(txtautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txteditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelid)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnumero)
                    .addComponent(txtnumeropagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelpublicação)
                    .addComponent(txtanopublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelclassificacao)
                    .addComponent(txtclassificacaoindicativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelpreco)
                    .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelidioma)
                    .addComponent(txtidioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncadastrar)
                    .addComponent(btnatualizar)
                    .addComponent(btndeletar)
                    .addComponent(btnconsultarId))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblmensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labeltitulo)
                        .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(labelautor)
                    .addGap(18, 18, 18)
                    .addComponent(labelgenero)
                    .addGap(32, 32, 32)
                    .addComponent(labeleditora)
                    .addContainerGap(406, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        // TODO add your handling code here:
        Livro objLivro = Livro.getBuilder()
        .comTitulo(txttitulo.getText())
        .comAutor(txtautor.getText())
        .comGenero(txtgenero.getText())
        .comEditora(txteditora.getText())
        .comIdioma(txtidioma.getText())
        .comNumeroPaginas(Integer.parseInt(txtnumeropagina.getText()))
        .comAnoPublicacao(Integer.parseInt(txtanopublicacao.getText()))
        .comClassificacaoIndicativa(txtclassificacaoindicativa.getText())
        .comPreco(Double.parseDouble(txtpreco.getText()))
        .constroi();

        ControleFacadeDesktop cfd = new ControleFacadeDesktop();
        lblmensagem.setText(cfd.acionarCadastrar(objLivro));
    }//GEN-LAST:event_btncadastrarActionPerformed

    private void txtanopublicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanopublicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanopublicacaoActionPerformed

    private void btnatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizarActionPerformed
        // TODO add your handling code here:
        Livro objLivro = Livro.getBuilder()
        .comTitulo(txttitulo.getText())
        .comAutor(txtautor.getText())
        .comGenero(txtgenero.getText())
        .comEditora(txteditora.getText())
        .comIdioma(txtidioma.getText())
        .comNumeroPaginas(Integer.parseInt(txtnumeropagina.getText()))
        .comAnoPublicacao(Integer.parseInt(txtanopublicacao.getText()))
        .comClassificacaoIndicativa(txtclassificacaoindicativa.getText())
        .comPreco(Double.parseDouble(txtpreco.getText()))
        .constroi();

        ControleFacadeDesktop cfd = new ControleFacadeDesktop();
        lblmensagem.setText(cfd.acionarAtualizar(objLivro));
    }//GEN-LAST:event_btnatualizarActionPerformed

    private void btndeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletarActionPerformed
        // TODO add your handling code here:
        Livro objLivro = Livro.getBuilder().comId(Integer.parseInt(txtid.getText())).constroi();
        
        ControleFacadeDesktop cfd = new ControleFacadeDesktop();
        lblmensagem.setText(cfd.acionarDeletar(objLivro));
    }//GEN-LAST:event_btndeletarActionPerformed

    private void btnconsultarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarIdActionPerformed
        // TODO add your handling code here:
        Livro objLivro = Livro.getBuilder().comId(Integer.parseInt(txtid.getText())).constroi();
        
        ControleFacadeDesktop cfd = new ControleFacadeDesktop();
        Livro objLivro2 = cfd.acionarConsultarPorId(objLivro);
        
        labelautor.setText(objLivro2.getAutor());
        labelclassificacao.setText(objLivro2.getClassificacaoIndicativa());
        labeleditora.setText(objLivro2.getEditora());
        labelgenero.setText(objLivro2.getGenero());
        labelidioma.setText(objLivro2.getIdioma());
        labelautor.setText(objLivro2.getAutor());
        labelautor.setText(objLivro2.getAutor());
        labeltitulo.setText(objLivro2.getTitulo());
    }//GEN-LAST:event_btnconsultarIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Livro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatualizar;
    private javax.swing.JButton btncadastrar;
    private javax.swing.JButton btnconsultarId;
    private javax.swing.JButton btndeletar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelautor;
    private javax.swing.JLabel labelclassificacao;
    private javax.swing.JLabel labeleditora;
    private javax.swing.JLabel labelgenero;
    private javax.swing.JLabel labelid;
    private javax.swing.JLabel labelidioma;
    private javax.swing.JLabel labelnumero;
    private javax.swing.JLabel labelpreco;
    private javax.swing.JLabel labelpublicação;
    private javax.swing.JLabel labeltitulo;
    private javax.swing.JLabel lblmensagem;
    private javax.swing.JTextField txtanopublicacao;
    private javax.swing.JTextField txtautor;
    private javax.swing.JTextField txtclassificacaoindicativa;
    private javax.swing.JTextField txteditora;
    private javax.swing.JTextField txtgenero;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidioma;
    private javax.swing.JTextField txtnumeropagina;
    private javax.swing.JTextField txtpreco;
    private javax.swing.JTextField txttitulo;
    // End of variables declaration//GEN-END:variables
}
